// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi5LXCHQuCAaOMNbcm5HjOA7iZ1w7d7_w',
    appId: '1:520949233881:web:5110b629c7a07d0dcba6c8',
    messagingSenderId: '520949233881',
    projectId: 'fir-flutter-codelab-2b884',
    authDomain: 'fir-flutter-codelab-2b884.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-2b884.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPzprDlsQKH5hVF8A4OzP4f9HRfkYYdr8',
    appId: '1:520949233881:android:9237cb7d8c446ca6cba6c8',
    messagingSenderId: '520949233881',
    projectId: 'fir-flutter-codelab-2b884',
    storageBucket: 'fir-flutter-codelab-2b884.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAT8JPqFkltmmkfN7i6fe-hblc9pRKDUc',
    appId: '1:520949233881:ios:285bcc4884c94bd4cba6c8',
    messagingSenderId: '520949233881',
    projectId: 'fir-flutter-codelab-2b884',
    storageBucket: 'fir-flutter-codelab-2b884.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAT8JPqFkltmmkfN7i6fe-hblc9pRKDUc',
    appId: '1:520949233881:ios:285bcc4884c94bd4cba6c8',
    messagingSenderId: '520949233881',
    projectId: 'fir-flutter-codelab-2b884',
    storageBucket: 'fir-flutter-codelab-2b884.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi5LXCHQuCAaOMNbcm5HjOA7iZ1w7d7_w',
    appId: '1:520949233881:web:b42f6f3a5410cf0bcba6c8',
    messagingSenderId: '520949233881',
    projectId: 'fir-flutter-codelab-2b884',
    authDomain: 'fir-flutter-codelab-2b884.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-2b884.firebasestorage.app',
  );

}